services:
  iris:
    #image: containers.intersystems.com/intersystems/iris-community:latest-cd
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["9095:52773","9092:1972"]
    container_name: iristest1
    volumes: ["./data:/data","./src:/src"]
    environment: 
      - TZ=JST-9

  webgateway:
    image: containers.intersystems.com/intersystems/webgateway:latest-cd
    container_name: wgtest1
    init: true
    ports:
      - 8090:80
      #- 8443:443
    environment:
    - ISC_CSP_CONF_FILE=/webgateway-shared/CSP.conf
    - ISC_CSP_INI_FILE=/webgateway-shared/CSP.ini
    volumes:
    - ./webgateway:/webgateway-shared    